# Generated by Django 2.2.3 on 2019-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='terrain',
            field=models.TextField(),
        ),
    ]
