# Generated by Django 2.2.3 on 2019-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191114_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text_posts',
            field=models.TextField(default='Text', max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='terrain',
            field=models.CharField(default='City', max_length=255),
        ),
    ]
