# Generated by Django 2.2.3 on 2020-01-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191122_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='text_posts',
            new_name='fname',
        ),
    ]
