# Generated by Django 2.2.3 on 2020-01-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200121_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='fname',
            field=models.TextField(default='Text'),
        ),
    ]
