# Generated by Django 3.0.4 on 2020-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200128_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FileField(default='null', null=True, upload_to='images'),
        ),
    ]
