# Generated by Django 3.0.4 on 2020-04-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200425_1458'),
    ]

    operations = [
        migrations.RemoveField('posts', 'posx'),
        migrations.RemoveField('posts', 'posy'),
        migrations.RemoveField('posts', 'posz')
    ]
