# Generated by Django 3.0.4 on 2020-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200425_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posx',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posts',
            name='posy',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='posts',
            name='posz',
            field=models.DecimalField(decimal_places=1, default=-3.8, max_digits=10),
        ),
    ]
